name: Build Godot Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy netlify.toml
        run: |
          mkdir $GITHUB_WORKSPACE/build
          cp $GITHUB_WORKSPACE/netlify.toml $GITHUB_WORKSPACE/build
      - name: Build Godot
        id: build-godot
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: index.html
          preset: HTML5
      - name: Install netlify client
        run: npm install netlify
      - name: Deploy to Netlify
        env:
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ vars.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --dir=$GITHUB_WORKSPACE/build --prod